ci: husky updated

diff --git a/.husky/_post-commit b/.husky/_post-commit
--- a/.husky/_post-commit
+++ b/.husky/_post-commit
@@ -5,6 +5,17 @@ if [ -e "$PWD/.husky/post-commit" ]
 then
     mv "$PWD/.husky/post-commit" "$PWD/.husky/_post-commit"
 fi
-git add .
-git commit --amend -C HEAD --no-verify
+
+
+{ # try
+
+    git add package.json package-lock.json &&
+    git commit --amend -C HEAD --no-verify
+
+} || { # catch
+    echo "FAILED AMEND -- MERGE?"
+    git reset HEAD &&
+    git checkout .
+}
+
 exit 0
